Category.create!(name: "Baby Care Essentials")
Category.create!(name: "Baby Carriers")
Category.create!(name: "Bathtime")
Category.create!(name: "Bedding & Nursery")
Category.create!(name: "Books, Music, & DVDs")
Category.create!(name: "Car Seats")
Category.create!(name: "Clothing")
Category.create!(name: "Cribs")
Category.create!(name: "Diaper Bags")
Category.create!(name: "Furniture")
Category.create!(name: "Health & Safety")
Category.create!(name: "Miscellaneous")
Category.create!(name: "Play Yards")
Category.create!(name: "Strollers & Travel Systems")
Category.create!(name: "Toys")